//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitachiSPACEProgramme.HitachiSPACEProgramme.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HitachiSPACEProgramme.HitachiSPACEProgramme.Languages.de.language", typeof(de_language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzeptable Wolkenarten:.
        /// </summary>
        internal static string AcceptableClouds {
            get {
                return ResourceManager.GetString("AcceptableClouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzeptable Wolkenarten erfolgreich geändert..
        /// </summary>
        internal static string AcceptableCloudTypesSuccess {
            get {
                return ResourceManager.GetString("AcceptableCloudTypesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitze akzeptieren:.
        /// </summary>
        internal static string AcceptLightnings {
            get {
                return ResourceManager.GetString("AcceptLightnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzeptieren Sie Blitze? (Ja/Nein):.
        /// </summary>
        internal static string AcceptLightningsPrompt {
            get {
                return ResourceManager.GetString("AcceptLightningsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitz akzeptieren auf Nein gesetzt..
        /// </summary>
        internal static string AcceptLightningsSetNo {
            get {
                return ResourceManager.GetString("AcceptLightningsSetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blitz akzeptieren auf Ja gesetzt..
        /// </summary>
        internal static string AcceptLightningsSetYes {
            get {
                return ResourceManager.GetString("AcceptLightningsSetYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bester Raumhafen: {0}, Tag: {1}.
        /// </summary>
        internal static string BestSpaceport_Message {
            get {
                return ResourceManager.GetString("BestSpaceport_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie die Nummer des Kriteriums ein, das Sie ändern möchten, oder 0, wenn Sie keine Änderungen vornehmen möchten:.
        /// </summary>
        internal static string ChangeCriteriaPrompt {
            get {
                return ResourceManager.GetString("ChangeCriteriaPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie Ihren E-Mail-Dienstanbieter: (Wenn Sie Gmail wählen, erhalten Sie Ihr App-Passwort).
        /// </summary>
        internal static string ChooseEmailProvider {
            get {
                return ResourceManager.GetString("ChooseEmailProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzeptable Wolkenarten erfolgreich geändert..
        /// </summary>
        internal static string CloudTypesChanged {
            get {
                return ResourceManager.GetString("CloudTypesChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie die akzeptablen Wolkenarten ein (durch Komma getrennt):.
        /// </summary>
        internal static string CloudTypesPrompt {
            get {
                return ResourceManager.GetString("CloudTypesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein, fahren Sie mit den aktuellen Kriterien fort.
        /// </summary>
        internal static string Criteria_ContinueOption {
            get {
                return ResourceManager.GetString("Criteria_ContinueOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja, ich möchte Kriterien für eine bestimmte Datei ändern.
        /// </summary>
        internal static string Criteria_ModifyFileOption {
            get {
                return ResourceManager.GetString("Criteria_ModifyFileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie Kriterien ändern?[1/2/3/4].
        /// </summary>
        internal static string Criteria_ModifyPrompt {
            get {
                return ResourceManager.GetString("Criteria_ModifyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein, aktuelle Kriterien anzeigen.
        /// </summary>
        internal static string Criteria_NoOption {
            get {
                return ResourceManager.GetString("Criteria_NoOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja, Kriterien ändern.
        /// </summary>
        internal static string Criteria_YesOption {
            get {
                return ResourceManager.GetString("Criteria_YesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfe Datei: {0}.
        /// </summary>
        internal static string CriteriaFile_Checking {
            get {
                return ResourceManager.GetString("CriteriaFile_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie die Kriterien für die Datei ein: {0}.
        /// </summary>
        internal static string CriteriaFile_EnterCriteria {
            get {
                return ResourceManager.GetString("CriteriaFile_EnterCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie die Kriterien für die Datei ändern [Ja/Nein]: {0}.
        /// </summary>
        internal static string CriteriaFile_Prompt {
            get {
                return ResourceManager.GetString("CriteriaFile_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Kriterienwerte:.
        /// </summary>
        internal static string CurrentCriteria {
            get {
                return ResourceManager.GetString("CurrentCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden der E-Mail fehlgeschlagen. Fehlermeldung: {0}.
        /// </summary>
        internal static string EmailFailed {
            get {
                return ResourceManager.GetString("EmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail erfolgreich gesendet..
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie Ihre Auswahl ein: .
        /// </summary>
        internal static string EnterChoice {
            get {
                return ResourceManager.GetString("EnterChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Adresse des Empfängers eingeben:.
        /// </summary>
        internal static string EnterReceiverEmail {
            get {
                return ResourceManager.GetString("EnterReceiverEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Adresse des Absenders eingeben:.
        /// </summary>
        internal static string EnterSenderEmail {
            get {
                return ResourceManager.GetString("EnterSenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort des Absenders eingeben:.
        /// </summary>
        internal static string EnterSenderPassword {
            get {
                return ResourceManager.GetString("EnterSenderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Schreiben des Startanalysenberichts: {0}.
        /// </summary>
        internal static string ErrorWritingReport {
            get {
                return ResourceManager.GetString("ErrorWritingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angegebener Ordner existiert nicht..
        /// </summary>
        internal static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angegebene Ordner existiert nicht..
        /// </summary>
        internal static string FolderPath_Error {
            get {
                return ResourceManager.GetString("FolderPath_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Ordnerpfad mit den Wettervorhersagen ein:.
        /// </summary>
        internal static string FolderPath_Prompt {
            get {
                return ResourceManager.GetString("FolderPath_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählter Ordner: {0}.
        /// </summary>
        internal static string FolderPath_Selected {
            get {
                return ResourceManager.GetString("FolderPath_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein unerwarteter Fehler ist aufgetreten:.
        /// </summary>
        internal static string FolderPath_UnexpectedError {
            get {
                return ResourceManager.GetString("FolderPath_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Hallo! Sie sind dabei, einen Launch-Analysebericht zu erstellen und zu versenden.
        ///
        ///    Um erfolgreich fortzufahren, benötigen Sie CSV-Dateien.
        ///
        ///    Bitte stellen Sie sicher, dass jede Datei nach dem Speicherort benannt ist, den sie repräsentiert, zum Beispiel: Kourou.csv.
        ///    Es ist wichtig zu beachten, dass die Analyse nur dann funktioniert, wenn wir alle Dateien im richtigen Format haben!
        ///
        ///    Wenn Sie bereit sind, können wir fortfahren..
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Wolkenart: {0}. Bitte geben Sie eine der folgenden ein: Cumulus, Stratus, Nimbus, Cirrus..
        /// </summary>
        internal static string InvalidCloudType {
            get {
                return ResourceManager.GetString("InvalidCloudType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Wolkentyp {0}  für Tag {1}. Bitte geben Sie einen der folgenden Wolkentypen an: Cirrus, Stratus, Cumulus, Nimbus..
        /// </summary>
        internal static string InvalidDataCloudType {
            get {
                return ResourceManager.GetString("InvalidDataCloudType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Ungültiges Datenformat in der Datei. {0}.
        /// </summary>
        internal static string InvalidDataFormatErrorMessage {
            get {
                return ResourceManager.GetString("InvalidDataFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Datenformat für den Tag {0}. Bitte geben Sie Daten für alle 16 Parameter an..
        /// </summary>
        internal static string InvalidDataFormatForDay {
            get {
                return ResourceManager.GetString("InvalidDataFormatForDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Datenformat für Parameter {0}, Tag {1}. Bitte geben Sie eine gültige Ganzzahl an..
        /// </summary>
        internal static string InvalidDataFormatForDayParameter {
            get {
                return ResourceManager.GetString("InvalidDataFormatForDayParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Datenformat für Blitz am Tag {0}. Bitte geben Sie &apos;Yes&apos; oder &apos;No&apos; an..
        /// </summary>
        internal static string InvalidDataFormatForLightning {
            get {
                return ResourceManager.GetString("InvalidDataFormatForLightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Datenformat für die Temperatur am Tag {0}. Bitte geben Sie eine gültige Ganzzahl an..
        /// </summary>
        internal static string InvalidDataFormatForTemperature {
            get {
                return ResourceManager.GetString("InvalidDataFormatForTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige E-Mail-Adresse. Bitte geben Sie eine gültige E-Mail-Adresse ein..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Eingabe. Bitte geben Sie eine gültige Nummer ein..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Eingabe. Bitte geben Sie &apos;Ja&apos; oder &apos;Nein&apos; ein..
        /// </summary>
        internal static string InvalidLightningsInput {
            get {
                return ResourceManager.GetString("InvalidLightningsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Anzahl von Zeilen in der Datei. Bitte geben Sie eine Datei mit genau 7 Zeilen an..
        /// </summary>
        internal static string InvalidNumberOfLines {
            get {
                return ResourceManager.GetString("InvalidNumberOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Passwort. Bitte geben Sie ein gültiges Passwort ein..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie die Sprache ein, mit der Sie fortfahren möchten (EN oder DE).
        /// </summary>
        internal static string Language_Prompt {
            get {
                return ResourceManager.GetString("Language_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale Luftfeuchtigkeit:.
        /// </summary>
        internal static string MaxHumidity {
            get {
                return ResourceManager.GetString("MaxHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den neuen Wert für die maximale Luftfeuchtigkeit ein:.
        /// </summary>
        internal static string MaxHumidityPrompt {
            get {
                return ResourceManager.GetString("MaxHumidityPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Luftfeuchtigkeit erfolgreich geändert..
        /// </summary>
        internal static string MaxHumiditySuccess {
            get {
                return ResourceManager.GetString("MaxHumiditySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale Niederschlagswahrscheinlichkeit:.
        /// </summary>
        internal static string MaxPrecipitation {
            get {
                return ResourceManager.GetString("MaxPrecipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den neuen Wert für die maximale Niederschlagswahrscheinlichkeit ein:.
        /// </summary>
        internal static string MaxPrecipitationPrompt {
            get {
                return ResourceManager.GetString("MaxPrecipitationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Niederschlag erfolgreich geändert..
        /// </summary>
        internal static string MaxPrecipitationSuccess {
            get {
                return ResourceManager.GetString("MaxPrecipitationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höchsttemperatur:.
        /// </summary>
        internal static string MaxTemperature {
            get {
                return ResourceManager.GetString("MaxTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den neuen Wert für die Höchsttemperatur ein:.
        /// </summary>
        internal static string MaxTemperaturePrompt {
            get {
                return ResourceManager.GetString("MaxTemperaturePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die maximale Temperatur wurde erfolgreich geändert..
        /// </summary>
        internal static string MaxTemperatureSuccess {
            get {
                return ResourceManager.GetString("MaxTemperatureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale Windgeschwindigkeit:.
        /// </summary>
        internal static string MaxWind {
            get {
                return ResourceManager.GetString("MaxWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den neuen Wert für die maximale Windgeschwindigkeit ein:.
        /// </summary>
        internal static string MaxWindPrompt {
            get {
                return ResourceManager.GetString("MaxWindPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert für die maximale Windgeschwindigkeit wurde erfolgreich geändert..
        /// </summary>
        internal static string MaxWindSuccess {
            get {
                return ResourceManager.GetString("MaxWindSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindesttemperatur:.
        /// </summary>
        internal static string MinTemperature {
            get {
                return ResourceManager.GetString("MinTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den neuen Wert für die Mindesttemperatur ein:.
        /// </summary>
        internal static string MinTemperaturePrompt {
            get {
                return ResourceManager.GetString("MinTemperaturePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Mindesttemperatur wurde erfolgreich geändert..
        /// </summary>
        internal static string MinTemperatureSuccess {
            get {
                return ResourceManager.GetString("MinTemperatureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den neuen Wert für.
        /// </summary>
        internal static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nein.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden keine Änderungen vorgenommen..
        /// </summary>
        internal static string NoChangesMade {
            get {
                return ResourceManager.GetString("NoChangesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der ausgewählte Ordner enthält keine .csv-Dateien..
        /// </summary>
        internal static string NoCSVFiles {
            get {
                return ResourceManager.GetString("NoCSVFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort erforderlich..
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Adresse des Empfängers erforderlich..
        /// </summary>
        internal static string ReceiverEmail {
            get {
                return ResourceManager.GetString("ReceiverEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startanalysenbericht erfolgreich erstellt unter: {0}.
        /// </summary>
        internal static string ReportCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ReportCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Adresse des Absenders erforderlich..
        /// </summary>
        internal static string SenderEmail {
            get {
                return ResourceManager.GetString("SenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl des SMTP-Servers erforderlich..
        /// </summary>
        internal static string SMTPSelection {
            get {
                return ResourceManager.GetString("SMTPSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein unerwarteter Fehler ist beim Abrufen des Ordners und der CSV-Dateien aufgetreten: {0}.
        /// </summary>
        internal static string UnexpectedErrorGetFolder {
            get {
                return ResourceManager.GetString("UnexpectedErrorGetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein unerwarteter Fehler ist aufgetreten: {0}.
        /// </summary>
        internal static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Raumhafen: {0}. Entfernung kann nicht berechnet werden..
        /// </summary>
        internal static string UnknownSpaceport {
            get {
                return ResourceManager.GetString("UnknownSpaceport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Überprüfen der Wetterbedingungen ist ein Fehler aufgetreten. Bitte geben Sie einen anderen Dateipfad ein..
        /// </summary>
        internal static string WeatherCheck_Error {
            get {
                return ResourceManager.GetString("WeatherCheck_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
