//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitachiSPACEProgramme.HitachiSPACEProgramme.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HitachiSPACEProgramme.HitachiSPACEProgramme.Languages.en.language", typeof(en_language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable Cloud Types:.
        /// </summary>
        internal static string AcceptableClouds {
            get {
                return ResourceManager.GetString("AcceptableClouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable cloud types changed successfully..
        /// </summary>
        internal static string AcceptableCloudTypesSuccess {
            get {
                return ResourceManager.GetString("AcceptableCloudTypesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Lightnings:.
        /// </summary>
        internal static string AcceptLightnings {
            get {
                return ResourceManager.GetString("AcceptLightnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept lightnings? (Yes/No):.
        /// </summary>
        internal static string AcceptLightningsPrompt {
            get {
                return ResourceManager.GetString("AcceptLightningsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept lightnings set to No..
        /// </summary>
        internal static string AcceptLightningsSetNo {
            get {
                return ResourceManager.GetString("AcceptLightningsSetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept lightnings set to Yes..
        /// </summary>
        internal static string AcceptLightningsSetYes {
            get {
                return ResourceManager.GetString("AcceptLightningsSetYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Spaceport: {0}, Day: {1}.
        /// </summary>
        internal static string BestSpaceport_Message {
            get {
                return ResourceManager.GetString("BestSpaceport_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of the criteria you want to change or 0 if you dont want to make changes:.
        /// </summary>
        internal static string ChangeCriteriaPrompt {
            get {
                return ResourceManager.GetString("ChangeCriteriaPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your email service provider: (If you choose Gmail get your app password).
        /// </summary>
        internal static string ChooseEmailProvider {
            get {
                return ResourceManager.GetString("ChooseEmailProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable cloud types changed successfully..
        /// </summary>
        internal static string CloudTypesChanged {
            get {
                return ResourceManager.GetString("CloudTypesChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the acceptable cloud types (comma-separated):.
        /// </summary>
        internal static string CloudTypesPrompt {
            get {
                return ResourceManager.GetString("CloudTypesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, continue with current criteria.
        /// </summary>
        internal static string Criteria_ContinueOption {
            get {
                return ResourceManager.GetString("Criteria_ContinueOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I want to modify a criteria for specific file.
        /// </summary>
        internal static string Criteria_ModifyFileOption {
            get {
                return ResourceManager.GetString("Criteria_ModifyFileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to modify any criteria?[1/2/3/4].
        /// </summary>
        internal static string Criteria_ModifyPrompt {
            get {
                return ResourceManager.GetString("Criteria_ModifyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, show current criteria.
        /// </summary>
        internal static string Criteria_NoOption {
            get {
                return ResourceManager.GetString("Criteria_NoOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, modify criteria.
        /// </summary>
        internal static string Criteria_YesOption {
            get {
                return ResourceManager.GetString("Criteria_YesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking file: {0}.
        /// </summary>
        internal static string CriteriaFile_Checking {
            get {
                return ResourceManager.GetString("CriteriaFile_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter criteria for file: {0}.
        /// </summary>
        internal static string CriteriaFile_EnterCriteria {
            get {
                return ResourceManager.GetString("CriteriaFile_EnterCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change criteria for file [Yes/No]: {0}.
        /// </summary>
        internal static string CriteriaFile_Prompt {
            get {
                return ResourceManager.GetString("CriteriaFile_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current criteria values:.
        /// </summary>
        internal static string CurrentCriteria {
            get {
                return ResourceManager.GetString("CurrentCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email. Error message: {0}.
        /// </summary>
        internal static string EmailFailed {
            get {
                return ResourceManager.GetString("EmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully..
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your choice: .
        /// </summary>
        internal static string EnterChoice {
            get {
                return ResourceManager.GetString("EnterChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter receiver&apos;s email address:.
        /// </summary>
        internal static string EnterReceiverEmail {
            get {
                return ResourceManager.GetString("EnterReceiverEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sender&apos;s email address:.
        /// </summary>
        internal static string EnterSenderEmail {
            get {
                return ResourceManager.GetString("EnterSenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sender&apos;s password:.
        /// </summary>
        internal static string EnterSenderPassword {
            get {
                return ResourceManager.GetString("EnterSenderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing launch analysis report: {0}.
        /// </summary>
        internal static string ErrorWritingReport {
            get {
                return ResourceManager.GetString("ErrorWritingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified folder does not exist..
        /// </summary>
        internal static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified folder does not exist..
        /// </summary>
        internal static string FolderPath_Error {
            get {
                return ResourceManager.GetString("FolderPath_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the folder path containing weather forecasts:.
        /// </summary>
        internal static string FolderPath_Prompt {
            get {
                return ResourceManager.GetString("FolderPath_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected folder: {0}.
        /// </summary>
        internal static string FolderPath_Selected {
            get {
                return ResourceManager.GetString("FolderPath_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred:.
        /// </summary>
        internal static string FolderPath_UnexpectedError {
            get {
                return ResourceManager.GetString("FolderPath_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Hello! You are about to create and send a Launch Analysis Report.
        ///    To proceed successfully, you will need .csv files.
        ///    Please ensure that each file is named after the location it represents, for example: Kourou.csv.
        ///    It&apos;s important to note that the analysis will not work unless we have all files in the correct format!
        ///    If you&apos;re ready, we can proceed..
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cloud type: {0}. Please enter one of the following: Cumulus, Stratus, Nimbus, Cirrus..
        /// </summary>
        internal static string InvalidCloudType {
            get {
                return ResourceManager.GetString("InvalidCloudType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cloud type {0} on Day {1}. Please provide one of the following: Cirrus, Stratus, Cumulus, Nimbus..
        /// </summary>
        internal static string InvalidDataCloudType {
            get {
                return ResourceManager.GetString("InvalidDataCloudType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid data format in the file. {0}.
        /// </summary>
        internal static string InvalidDataFormatErrorMessage {
            get {
                return ResourceManager.GetString("InvalidDataFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data format for Day {0}. Please provide data for all 16 parameters..
        /// </summary>
        internal static string InvalidDataFormatForDay {
            get {
                return ResourceManager.GetString("InvalidDataFormatForDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data format for Parameter {0}, Day {1}. Please provide a valid integer..
        /// </summary>
        internal static string InvalidDataFormatForDayParameter {
            get {
                return ResourceManager.GetString("InvalidDataFormatForDayParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data format for Lightning on Day {0}. Please provide &apos;Yes&apos; or &apos;No&apos;..
        /// </summary>
        internal static string InvalidDataFormatForLightning {
            get {
                return ResourceManager.GetString("InvalidDataFormatForLightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data format for Temperature on Day {0}. Please provide a valid integer..
        /// </summary>
        internal static string InvalidDataFormatForTemperature {
            get {
                return ResourceManager.GetString("InvalidDataFormatForTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address. Please enter a valid email address..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a valid number..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter &apos;Yes&apos; or &apos;No&apos;..
        /// </summary>
        internal static string InvalidLightningsInput {
            get {
                return ResourceManager.GetString("InvalidLightningsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of lines in the file. Please provide a file with exactly 7 lines..
        /// </summary>
        internal static string InvalidNumberOfLines {
            get {
                return ResourceManager.GetString("InvalidNumberOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password. Please enter a valid password..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the language you want to continue with (EN or DE).
        /// </summary>
        internal static string Language_Prompt {
            get {
                return ResourceManager.GetString("Language_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Humidity:.
        /// </summary>
        internal static string MaxHumidity {
            get {
                return ResourceManager.GetString("MaxHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new value for Max Humidity:.
        /// </summary>
        internal static string MaxHumidityPrompt {
            get {
                return ResourceManager.GetString("MaxHumidityPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Humidity changed successfully..
        /// </summary>
        internal static string MaxHumiditySuccess {
            get {
                return ResourceManager.GetString("MaxHumiditySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Precipitation:.
        /// </summary>
        internal static string MaxPrecipitation {
            get {
                return ResourceManager.GetString("MaxPrecipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new value for Max Precipitation:.
        /// </summary>
        internal static string MaxPrecipitationPrompt {
            get {
                return ResourceManager.GetString("MaxPrecipitationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Precipitation changed successfully..
        /// </summary>
        internal static string MaxPrecipitationSuccess {
            get {
                return ResourceManager.GetString("MaxPrecipitationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Temperature:.
        /// </summary>
        internal static string MaxTemperature {
            get {
                return ResourceManager.GetString("MaxTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new value for Max Temperature:.
        /// </summary>
        internal static string MaxTemperaturePrompt {
            get {
                return ResourceManager.GetString("MaxTemperaturePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Temperature changed successfully..
        /// </summary>
        internal static string MaxTemperatureSuccess {
            get {
                return ResourceManager.GetString("MaxTemperatureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Wind:.
        /// </summary>
        internal static string MaxWind {
            get {
                return ResourceManager.GetString("MaxWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new value for Max Wind:.
        /// </summary>
        internal static string MaxWindPrompt {
            get {
                return ResourceManager.GetString("MaxWindPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Wind changed successfully..
        /// </summary>
        internal static string MaxWindSuccess {
            get {
                return ResourceManager.GetString("MaxWindSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Temperature:.
        /// </summary>
        internal static string MinTemperature {
            get {
                return ResourceManager.GetString("MinTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new value for Min Temperature:.
        /// </summary>
        internal static string MinTemperaturePrompt {
            get {
                return ResourceManager.GetString("MinTemperaturePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Temperature changed successfully..
        /// </summary>
        internal static string MinTemperatureSuccess {
            get {
                return ResourceManager.GetString("MinTemperatureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new value for .
        /// </summary>
        internal static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Changes were made..
        /// </summary>
        internal static string NoChangesMade {
            get {
                return ResourceManager.GetString("NoChangesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder does not contain any .csv files..
        /// </summary>
        internal static string NoCSVFiles {
            get {
                return ResourceManager.GetString("NoCSVFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver&apos;s email address is required..
        /// </summary>
        internal static string ReceiverEmail {
            get {
                return ResourceManager.GetString("ReceiverEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch analysis report created successfully at: {0}.
        /// </summary>
        internal static string ReportCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ReportCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender&apos;s email address is required..
        /// </summary>
        internal static string SenderEmail {
            get {
                return ResourceManager.GetString("SenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP server selection is required..
        /// </summary>
        internal static string SMTPSelection {
            get {
                return ResourceManager.GetString("SMTPSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while getting folder and CSV files: {0}.
        /// </summary>
        internal static string UnexpectedErrorGetFolder {
            get {
                return ResourceManager.GetString("UnexpectedErrorGetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: {0}.
        /// </summary>
        internal static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown spaceport: {0}. Cannot calculate distance..
        /// </summary>
        internal static string UnknownSpaceport {
            get {
                return ResourceManager.GetString("UnknownSpaceport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking weather conditions. Please enter another file path..
        /// </summary>
        internal static string WeatherCheck_Error {
            get {
                return ResourceManager.GetString("WeatherCheck_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
